[package]
name = "djikstra"
version = "0.1.0"
authors = ["Nytelife26 <xtylerjrx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
